---

- name: Define osp-prov network
  virt_net:
    state: active
    name: osp-prov
    xml: '{{ lookup("file", "osp-prov.xml") }}'
  tags: net

- name: Create root disk for nodes
  shell: qemu-img create -f qcow2 -o preallocation=metadata /var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}.qcow2 50G
  with_items: "{{ groups['overcloud'] }}"
  args:
    creates: /var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}.qcow2

- name: Create ceph osd disk
  shell: qemu-img create -f qcow2 -o preallocation=metadata /var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}-osd.qcow2 60G
  with_items: "{{ groups['overcloud'] }}"
  args:
    creates: /var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}-osd.qcow2
  when: ceph_osd is defined
  
- name: Generate libvirt xml for ceph nodes
  shell: virt-install --ram 10240 --vcpus 4 --os-variant rhel7 --disk path=/var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}.qcow2,device=disk,bus=virtio,format=qcow2  --disk path=/var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}-osd.qcow2,device=disk,bus=virtio,format=qcow2--noautoconsole --vnc --network network:{{ provisioning_network }} --name {{ hostvars[item]['inventory_hostname'] }} --dry-run --print-xml > /tmp/{{ hostvars[item]['inventory_hostname'] }}.xml
  with_items: "{{ groups['ceph'] }}"
  args:
    creates: /etc/libvirt/qemu/{{ hostvars[item]['inventory_hostname'] }}.xml

- name: Generate libvirt xml for compute and controllers
  shell: virt-install --ram 10240 --vcpus 4 --os-variant rhel7 --disk path=/var/lib/libvirt/images/{{ hostvars[item]['inventory_hostname'] }}.qcow2,device=disk,bus=virtio,format=qcow2 --noautoconsole --vnc --network network:{{ provisioning_network }} --name {{ hostvars[item]['inventory_hostname'] }} --dry-run --print-xml > /tmp/{{ hostvars[item]['inventory_hostname'] }}.xml
  with_items: "{{ groups['overcloud'] }}"
  args:
    creates: /etc/libvirt/qemu/{{ hostvars[item]['inventory_hostname'] }}.xml

- name: Define VM
  shell: virsh define /tmp/{{ hostvars[item]['inventory_hostname'] }}.xml
  with_items: "{{ groups['overcloud'] }}"
  args:
    creates: /etc/libvirt/qemu/{{ hostvars[item]['inventory_hostname'] }}.xml
