
- name: create the stack user
  user: name=stack 

- name: configure sudo for stack user
  copy: content="stack ALL=(root) NOPASSWD:ALL" dest=/etc/sudoers.d/stack force=no group=root owner=root mode=0644

- name: add director IP to /etc/hosts
  lineinfile: dest=/etc/hosts line='127.0.0.1 {{ ansible_fqdn }} {{ ansible_hostname }}'

- name: create images and templates directories
  file: path=/home/stack/{{ item }} state=directory mode=0775 owner=stack group=stack
  with_items:
    - templates
    - images

- name: perform yum update
  yum:
    name: "*"
    state: latest
  register: yum_update

- name: reboot host
  shell: sleep 10 && /sbin/shutdown -r now
  async: 300
  poll: 0
  when: yum_update is changed

- name: wait for server to come back from reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 30
    timeout: 600
    state: started
  when: yum_update is changed

- name: install director packages
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - python-tripleoclient
    - rhosp-director-images
    - rhosp-director-images-ipa
    - libguestfs-tools
    - ceph-ansible

- name: unpack overcloud images
  unarchive: 
    src: /usr/share/rhosp-director-images/{{ item.tarfile }} 
    dest: /home/stack/images 
    copy: no
  creates: /home/stack/images/{{ item.filename }}
  with_items:
    - { "tarfile": "overcloud-full-latest-{{ rhosp_version }}.0.tar", "filename": overcloud-full.qcow2" }
    - { "tarfile": "ironic-python-agent-latest-{{ rhosp_version }}.0.tar", "filename": "ironic-python-agent.initramfs" }

- name: Run virt customize and set images root password
  shell: "export LIBGUESTFS_BACKEND=direct && virt-customize -a /home/stack/images/overcloud-full.qcow2 --root-password password:{{ root_password }}"

- name: copy undercloud.conf in place
  template: 
    src: undercloud_{{ rhosp_version }}.conf.j2 
    dest: /home/stack/undercloud.conf 
    owner: stack 
    group: stack

- name: install undercloud
  become: yes
  become_user: stack
  shell: openstack undercloud install
  args:
    creates: /home/stack/stackrc

- name: Create instackenv template
  template:
    src: instackenv.json.j2
    dest: /home/stack/instackenv.json
    owner: stack
    group: stack


#- name: Copy hieradata file in place
#  template: src=/ansible/roles/osp-director/templates/undercloud.yaml.j2 dest=/home/stack/undercloud.yaml

#- name: Define overcloud ironic nodes
#  become: yes
#  become_user: stack
#  shell: 'source /home/stack/stackrc ;  openstack baremetal import instackenv.json'
#  tags: osp-director

